### ISSUE TITLE
Server crash - NoSuchMethodError: epicsquid.mysticalworld.block.BlockThatch.setLayer(Lnet/minecraft/util/BlockRenderLayer;)Lepicsquid/mysticallib/block/BlockBase;

### ISSUE THREAD

**Issue by ProsperCraft** [EpicSquid/MysticalWorld#2]
https://gist.github.com/Potato-bot/51c349281bcba23ba936bdf2bd77c293

I just updated and this crashes on the server, but not in single player.

**Comment by EpicSquid** [comment]
New release on curseforge is being approved now. Fixed
