### ISSUE TITLE
Unidict + MysticalWorld + EmbersRekindled

### ISSUE THREAD

**Issue by terrapin47** [EpicSquid/MysticalWorld#5]
I have MysticalWorld with all the materials disabled, and Unidict set up with Embers Rekindled.  The block to 9x ingot recipes and vice versa show up in JEI, but do not work in the crafting table ( also ingot to 9x nugget ).  Removing MysticalWorld fixes the issue, but it also does not occur without Unidict present.

Dawnstone works fine, however.

Enabling all the MysticalWorld materials ( and letting unidict take care of removing the recipes ) also fixes the issue.

**Comment by duely** [comment]
Unidict is bad. End of story.
