### ISSUE TITLE
Ores still spawning even when disabled

### ISSUE THREAD

**Issue by ZeroArcana** [EpicSquid/MysticalWorld#6]
I've disabled all the metals through the config options (I have Immersive Engineering that adds some of the same ores), but I'm still seeing the Mystical World ores spawn in newly generated worlds (I have HWYLA displaying which mod the blocks are from); I've even tried disabling all the modules in the config, but the ores are still spawning. Even after setting all of the oregen values to 0, I'm still finding the Mystical World ores generating in new worlds. 

**EDIT:** Just tested a modded environment with only this mod active with the above changes (all metals disabled, all modules disabled, all oregen values set to 0), and the ores are still being generated.

**Comment by EpicSquid** [comment]
Which config option have u set to disable ore spawning?

**Comment by ZeroArcana** [comment]
I used the options available through Minecraft's "Mod Options" menu. 

[options menu images](https://imgur.com/a/9zVA1Wx)

**Comment by Martacus** [comment]
Can you check if the config in the config folder has changed accordingly?

**Comment by ZeroArcana** [comment]
> Can you check if the config in the config folder has changed accordingly?

Just checked; looks like the changes weren't being saved to the config file, even though Minecraft was saying they were. Weird. 

Disabling the ores through editing the config file directly seems to have fixed it.
