### ISSUE TITLE
Iron and gold dusts are created when dusts are disabled in config

### ISSUE THREAD

**Issue by nihiltres** [EpicSquid/MysticalWorld#7]
As the title says: iron and gold dusts, and "tiny" equivalents, are available even if disabled in the config, with

```
# Enable Dusts for Metals
B:enableDusts=false
```
This is at very least *confusing* behaviour; `enableDusts` only controls whether *modded* metals get dusts, but there's no opt-out* for *vanilla* ones. Please make dusts for vanilla metals respect the setting.

(*Well, aside from disabling the Mystical World module, but if you're using Mystical World, that isn't an option.)

**Comment by Martacus** [comment]
Thanks, I'll look into it.
